"""Regenerate README.md for a custom PReSto LiPD download.

Reads `query_params.json` and (if present) `cleaning_report.json` and
`README_NOTES.md` from the repo root, and writes a `README.md` that
surfaces the run-specific data selection, data-cleaning summary, and
any user-authored notes.

`README_NOTES.md` is the author's escape hatch — its contents are
inserted verbatim near the top of the README and survive regenerations.
Everything else in the README is a pure function of the input files, so
re-running with unchanged inputs is byte-stable.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


TEMPLATE_REPO = "https://github.com/DaveEdge1/lipd-downloads"
PRESTO_URL = "https://paleopresto.com"
LIPDVERSE_URL = "https://lipdverse.org"

MODE_DESCRIPTIONS = {
    "filtered": (
        "filtered (records hand-selected via PReSto's interactive map "
        "interface and queried from LiPDverse)"
    ),
    "archived": (
        "archived (a pre-built compilation pickle was downloaded directly "
        "from LiPDverse)"
    ),
}


def _format_compilations(raw):
    """'CoralHydro2k-1_0_0,Pages2k' → 'CoralHydro2k 1.0.0, Pages2k'."""
    if not raw:
        return None
    out = []
    for token in str(raw).split(","):
        token = token.strip()
        if not token:
            continue
        if "-" in token:
            name, _, version = token.partition("-")
            out.append(f"{name.strip()} {version.replace('_', '.').strip()}")
        else:
            out.append(token)
    return ", ".join(out)


def _split_csv(raw):
    """Parse a 'a,b,c' string (or list) into a clean list, dropping empties."""
    if raw is None or raw == "":
        return []
    if isinstance(raw, (list, tuple)):
        items = raw
    else:
        items = str(raw).split(",")
    return [str(x).strip() for x in items if str(x).strip()]


def _format_archives(value):
    if not value:
        return None
    if isinstance(value, (list, tuple)):
        return ", ".join(str(v) for v in value if v)
    return str(value)


def summarize_cleaning(report):
    """Aggregate a PReSto cleaning_report.json (list of duplicate groups).

    Returns a dict with `groups`, `considered`, `kept`, `removed`, and
    `top_reason` (string or None) — or None if the report is unrecognized.
    """
    if not isinstance(report, list) or not report:
        return None
    groups = len(report)
    considered = kept = removed = 0
    removals_by_reason = {}
    for group in report:
        if not isinstance(group, dict):
            continue
        records = group.get("records") or []
        considered += len(records)
        n_removed_here = 0
        for rec in records:
            decision = (rec.get("decision") or "").strip().lower()
            if decision == "keep":
                kept += 1
            elif decision == "remove":
                removed += 1
                n_removed_here += 1
        if n_removed_here:
            note = (group.get("notes") or "uncategorized").strip() or "uncategorized"
            removals_by_reason[note] = removals_by_reason.get(note, 0) + n_removed_here

    top_reason = None
    if removals_by_reason and removed:
        note, count = max(removals_by_reason.items(), key=lambda kv: kv[1])
        if count / removed >= 0.5:
            top_reason = (note, count)

    return {
        "groups": groups,
        "considered": considered,
        "kept": kept,
        "removed": removed,
        "top_reason": top_reason,
    }


def _cleaning_bullet(summary):
    if not summary or not summary["considered"]:
        return None
    parts = [
        f"{summary['considered']} records reviewed across "
        f"{summary['groups']} duplicate-detection groups; "
        f"{summary['removed']} removed"
    ]
    if summary["top_reason"]:
        note, count = summary["top_reason"]
        for prefix in ("removed by ", "removed "):
            if note.lower().startswith(prefix):
                note = note[len(prefix):]
                break
        parts.append(f" (predominantly *{note}* — {count} of {summary['removed']})")
    parts.append(
        ". See [`cleaning_report.json`](cleaning_report.json) for per-record decisions."
    )
    return (
        "**Data cleaning ([PReSto data-cleaning app]"
        f"({PRESTO_URL})):** " + "".join(parts)
    )


def build_readme(query, *, cleaning_report=None, user_notes=None,
                 releases_url=None):
    mode = (query.get("mode") or "").strip().lower()
    mode_desc = MODE_DESCRIPTIONS.get(mode, mode or "—")

    compilations = _format_compilations(query.get("compilation"))
    archive_types = _format_archives(query.get("archiveTypes"))

    tsids = query.get("tsids") or []
    removed_tsids = query.get("removedTsids") or []

    lines = []
    lines.append("# Custom LiPD Download")
    lines.append("")
    lines.append(
        f"This repository was generated by [PReSto]({PRESTO_URL}) "
        "(Paleoclimate Reconstruction Storehouse) from the "
        f"[LiPD Downloads Template]({TEMPLATE_REPO}). It downloads LiPD "
        f"records from [LiPDverse]({LIPDVERSE_URL}) over the parameters "
        "captured below."
    )
    lines.append("")

    notes_text = (user_notes or "").strip()
    if notes_text:
        lines.append(notes_text)
        lines.append("")

    lines.append("## Proxy data selection")
    lines.append("")
    lines.append(f"- **Mode:** {mode_desc}")
    if compilations:
        lines.append(f"- **Source compilations:** {compilations}")
    if archive_types:
        lines.append(f"- **Archive types requested:** {archive_types}")
    if tsids:
        lines.append(f"- **Records selected:** {len(tsids)}")
    if removed_tsids:
        lines.append(f"- **Records explicitly excluded:** {len(removed_tsids)}")
    cleaning_summary = summarize_cleaning(cleaning_report) if cleaning_report else None
    cleaning_bullet = _cleaning_bullet(cleaning_summary)
    if cleaning_bullet:
        lines.append(f"- {cleaning_bullet}")
    lines.append("")
    lines.append("(See `query_params.json` for the full TSID list.)")
    lines.append("")

    lines.append("## Downloaded data")
    lines.append("")
    if mode == "archived":
        lines.append(
            "- **Output:** `lipd_data.pkl` — the pre-built compilation "
            "pickle, downloaded directly from "
            f"`{LIPDVERSE_URL}/<compilation>/<version>/<compilation><version>.pkl`."
        )
    elif mode == "filtered":
        lines.append(
            "- **Output:** `lipd_files.zip` — a zip archive of raw `.lpd` "
            "files produced by the `lipdGenerator` Docker container "
            "(`davidedge/lipd_webapps:lipdGenerator`) from the records "
            "listed in `query_params.json`."
        )
    else:
        lines.append(
            "- **Output:** the LiPD data file produced by the workflow "
            "(see `.github/workflows/lipd-download.yml`)."
        )
    lines.append(
        "- The data and the inputs that produced it are uploaded as the "
        "`lipd-download-data-<run_id>` workflow artifact (90-day retention)."
    )
    lines.append("")

    if releases_url:
        lines.append("## Citation & archive")
        lines.append("")
        lines.append(
            "Each successful download is bundled into a tagged GitHub "
            f"Release named `download-<run_id>` at <{releases_url}>. The "
            "release preserves the LiPD data file, `query_params.json`, "
            "the cleaning report (if any), and the README snapshot — "
            "these survive beyond the 90-day Actions artifact retention "
            "so the download remains fully auditable and reproducible "
            "long after the workflow logs expire."
        )
        lines.append("")
        lines.append(
            "If [GitHub-Zenodo integration]"
            "(https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) "
            "is enabled on this repository, each release also receives a "
            "citable DOI, with a stable concept DOI for the download "
            "series as a whole."
        )
        lines.append("")

    lines.append("## Acknowledgements")
    lines.append("")
    lines.append(
        f"Built from the [PReSto LiPD Downloads Template]({TEMPLATE_REPO}) "
        "by [David Edge](https://orcid.org/0000-0001-6938-2850), "
        "[Michael Erb](https://orcid.org/0000-0002-1763-2522), "
        "[Nicholas McKay](https://orcid.org/0000-0003-3598-5113), "
        "[Deborah Khider](https://orcid.org/0000-0001-7501-8430), & "
        "[Julien Emile-Geay](https://orcid.org/0000-0001-5920-4751). "
        f"Hosted by [PReSto]({PRESTO_URL})."
    )
    lines.append("")

    lines.append("---")
    lines.append(
        "*This README is regenerated automatically by "
        "`scripts/generate_readme.py` from `query_params.json` and (if "
        "present) `cleaning_report.json`. Hand edits to this file will "
        "be overwritten on the next run — to add commentary that "
        "survives regenerations, write it in `README_NOTES.md` (created "
        "at repo root), where it will appear verbatim near the top of "
        "this page.*"
    )
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--query", default="query_params.json",
                        help="Path to query_params.json (default: %(default)s)")
    parser.add_argument("--cleaning-report", default="cleaning_report.json",
                        help="Path to cleaning_report.json; silently "
                             "skipped if missing (default: %(default)s)")
    parser.add_argument("--notes", default="README_NOTES.md",
                        help="Path to user-authored notes file inserted "
                             "verbatim near the top of the README; "
                             "silently skipped if missing "
                             "(default: %(default)s)")
    parser.add_argument("--pages-url",
                        help="Reserved for forward-compatibility with "
                             "sibling templates; currently unused.")
    parser.add_argument("--releases-url",
                        help="GitHub Releases URL for this repo, linked "
                             "from the Citation & archive section. When "
                             "omitted the section is suppressed.")
    parser.add_argument("--out", default="README.md",
                        help="Output README path (default: %(default)s)")
    args = parser.parse_args()

    query_path = Path(args.query)
    if not query_path.exists():
        print(f"ERROR: {query_path} not found", file=sys.stderr)
        return 1

    with query_path.open("r", encoding="utf-8") as f:
        query = json.load(f)

    cleaning_report = None
    cleaning_path = Path(args.cleaning_report)
    if cleaning_path.exists():
        try:
            with cleaning_path.open("r", encoding="utf-8") as f:
                cleaning_report = json.load(f)
        except (json.JSONDecodeError, OSError) as exc:
            print(f"WARN: could not parse {cleaning_path}: {exc}",
                  file=sys.stderr)

    user_notes = None
    notes_path = Path(args.notes)
    if notes_path.exists():
        try:
            user_notes = notes_path.read_text(encoding="utf-8")
        except OSError as exc:
            print(f"WARN: could not read {notes_path}: {exc}", file=sys.stderr)

    text = build_readme(
        query,
        cleaning_report=cleaning_report,
        user_notes=user_notes,
        releases_url=args.releases_url,
    )
    Path(args.out).write_text(text, encoding="utf-8")
    print(f"Wrote {args.out} ({len(text):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
